export enum IpcEvents {
  CLICK_TITLEBAR_MAC = 'CLICK_TITLEBAR_MAC',
  MONACO_EXECUTE_COMMAND = 'MONACO_EXECUTE_COMMAND',
  MONACO_TOGGLE_OPTION = 'MONACO_TOGGLE_OPTION',
  OPEN_SETTINGS = 'OPEN_SETTINGS',
  REDO_IN_EDITOR = 'REDO_IN_EDITOR',
  SAY_HELLO = 'SAY_HELLO',
  SELECT_ALL_IN_EDITOR = 'SELECT_ALL_IN_EDITOR',
  SET_NATIVE_THEME = 'SET_NATIVE_THEME',
  UNDO_IN_EDITOR = 'UNDO_IN_EDITOR',
}

export const ipcMainEvents = [
  IpcEvents.CLICK_TITLEBAR_MAC,
  IpcEvents.SAY_HELLO,
  IpcEvents.SET_NATIVE_THEME,
];
