export enum IpcEvents {
  CLICK_TITLEBAR_MAC = 'CLICK_TITLEBAR_MAC',
  FS_DELETE_FILE = 'FS_DELETE_FILE',
  FS_GET_FILES = 'FS_GET_FILES',
  FS_OPEN_FLUX = 'FS_OPEN_FLUX',
  GET_FILES = 'GET_FILES',
  MONACO_EXECUTE_COMMAND = 'MONACO_EXECUTE_COMMAND',
  MONACO_TOGGLE_OPTION = 'MONACO_TOGGLE_OPTION',
  OPEN_SETTINGS = 'OPEN_SETTINGS',
  PARSE_STRUCT = 'PARSE_STRUCT',
  PATH_EXISTS = 'PATH_EXISTS',
  REDO_IN_EDITOR = 'REDO_IN_EDITOR',
  SAVED_LOCAL_FLUX = 'SAVED_LOCAL_FLUX',
  SAY_HELLO = 'SAY_HELLO',
  SELECT_ALL_IN_EDITOR = 'SELECT_ALL_IN_EDITOR',
  SET_NATIVE_THEME = 'SET_NATIVE_THEME',
  UNDO_IN_EDITOR = 'UNDO_IN_EDITOR',
}

export const ipcMainEvents = [
  IpcEvents.CLICK_TITLEBAR_MAC,
  IpcEvents.FS_DELETE_FILE,
  IpcEvents.FS_GET_FILES,
  IpcEvents.PARSE_STRUCT,
  IpcEvents.SAY_HELLO,
  IpcEvents.SET_NATIVE_THEME,
];
